import { getPostBySlug, getCategories, getPosts } from '@/lib/wordpress';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ChevronRight, Home, Calendar, User, Clock } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TableOfContents from '@/components/TableOfContents';
import QualityMeter from '@/components/QualityMeter';
import PostSidebar from '@/components/PostSidebar';
import AuthorBio from '@/components/AuthorBio';
import PostNavigation from '@/components/PostNavigation';
import RelatedPosts from '@/components/RelatedPosts';
import Comments from '@/components/Comments';
import ReadingProgress from '@/components/ReadingProgress';
import { decodeHtml, toTitleCase } from '@/lib/utils';