import { getBlogPostBySlug, getCategories, getPosts } from '@/lib/wordpress';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { ChevronRight, Home, Calendar, User, Clock, ArrowLeft } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ReadingProgress from '@/components/ReadingProgress';
import TableOfContents from '@/components/TableOfContents';
import AuthorBio from '@/components/AuthorBio';
import PostSidebar from '@/components/PostSidebar';
import { decodeHtml } from '@/lib/utils';