import { getBlogPosts, getCategories, getPosts } from '@/lib/wordpress';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Sidebar from '@/components/Sidebar';
import Link from 'next/link';
import Image from 'next/image';
import { Calendar, ArrowRight, BookOpen, PenLine, Lightbulb } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { WPPost, WPCategory, PaginationInfo } from '@/lib/types';
import { decodeHtml } from '@/lib/utils';